name: check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - name: Install M2 Emacs package
        run: |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2
          sudo apt-get install -y --no-install-recommends elpa-macaulay2
          M2_PATH=/usr/share/emacs/site-lisp/elpa/macaulay2-$(M2 --version)
          echo "(add-to-list 'load-path \"$M2_PATH\")" > ~/.emacs
      - name: Run MELPA checks
        uses: leotaku/elisp-check@master
      - name: Install Macaulay2
        run: sudo apt-get install -y --no-install-recommends macaulay2
      - name: Install M2 package
        run: M2 -q --stop -e 'installPackage "ComintMime"; exit 0'
      - name: Test M2 package
        run: M2 -q --stop -e 'check needsPackage "ComintMime"; exit 0'
