name: check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - name: Install Macaulay2
        run: |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2
          sudo apt-get install -y --no-install-recommends \
              elpa-macaulay2 macaulay2
          M2_PATH=/usr/share/emacs/site-lisp/elpa-src/macaulay2-$(M2 --version)
          cd /usr/share/emacs/site-lisp && ln -s $M2_PATH/*.el .
      - name: Run MELPA checks
        uses: leotaku/elisp-check@master
      - name: Install M2 package
        run: M2 -q --stop -e 'installPackage "ComintMime"; exit 0'
      - name: Test M2 package
        run: M2 -q --stop -e 'check needsPackage "ComintMime"; exit 0'
